package com.wy.adalliance.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class SupermanMovieFileInfo implements Serializable {

	/**
	 * @mbggenerated
	 */
	private String movieFileId;
	/**
	 * @mbggenerated
	 */
	private String movieId;
	/**
	 * @mbggenerated
	 */
	private String movieFileName;
	/**
	 * @mbggenerated
	 */
	private String movieFilePicPath;
	/**
	 * @mbggenerated
	 */
	private String movieUrl;
	/**
	 * @mbggenerated
	 */
	private String magnet;
	/**
	 * @mbggenerated
	 */
	private Integer isCorrect;
	/**
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * @mbggenerated
	 */
	private String movieFileDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table superman_movie_file_info
	 * @mbggenerated  Mon Dec 05 16:36:46 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * @mbggenerated
	 */
	public String getMovieFileId() {
		return movieFileId;
	}

	/**
	 * @param movieFileId  
	 * @mbggenerated
	 */
	public void setMovieFileId(String movieFileId) {
		this.movieFileId = movieFileId == null ? null : movieFileId.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieId() {
		return movieId;
	}

	/**
	 * @param movieId  
	 * @mbggenerated
	 */
	public void setMovieId(String movieId) {
		this.movieId = movieId == null ? null : movieId.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieFileName() {
		return movieFileName;
	}

	/**
	 * @param movieFileName  
	 * @mbggenerated
	 */
	public void setMovieFileName(String movieFileName) {
		this.movieFileName = movieFileName == null ? null : movieFileName.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieFilePicPath() {
		return movieFilePicPath;
	}

	/**
	 * @param movieFilePicPath  
	 * @mbggenerated
	 */
	public void setMovieFilePicPath(String movieFilePicPath) {
		this.movieFilePicPath = movieFilePicPath == null ? null : movieFilePicPath.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieUrl() {
		return movieUrl;
	}

	/**
	 * @param movieUrl  
	 * @mbggenerated
	 */
	public void setMovieUrl(String movieUrl) {
		this.movieUrl = movieUrl == null ? null : movieUrl.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMagnet() {
		return magnet;
	}

	/**
	 * @param magnet  
	 * @mbggenerated
	 */
	public void setMagnet(String magnet) {
		this.magnet = magnet == null ? null : magnet.trim();
	}

	/**
	 * @mbggenerated
	 */
	public Integer getIsCorrect() {
		return isCorrect;
	}

	/**
	 * @param isCorrect  
	 * @mbggenerated
	 */
	public void setIsCorrect(Integer isCorrect) {
		this.isCorrect = isCorrect;
	}

	/**
	 * @mbggenerated
	 */
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * @param rowAddTime  
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieFileDescription() {
		return movieFileDescription;
	}

	/**
	 * @param movieFileDescription  
	 * @mbggenerated
	 */
	public void setMovieFileDescription(String movieFileDescription) {
		this.movieFileDescription = movieFileDescription == null ? null : movieFileDescription
			.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table superman_movie_file_info
	 * @mbggenerated  Mon Dec 05 16:36:46 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", movieFileId=").append(movieFileId);
		sb.append(", movieId=").append(movieId);
		sb.append(", movieFileName=").append(movieFileName);
		sb.append(", movieFilePicPath=").append(movieFilePicPath);
		sb.append(", movieUrl=").append(movieUrl);
		sb.append(", magnet=").append(magnet);
		sb.append(", isCorrect=").append(isCorrect);
		sb.append(", rowAddTime=").append(rowAddTime);
		sb.append(", movieFileDescription=").append(movieFileDescription);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}