package com.wy.adalliance.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class SupermanMovie implements Serializable {

	/**
	 * @mbggenerated
	 */
	private String movieId;
	/**
	 * @mbggenerated
	 */
	private String movieName;
	/**
	 * @mbggenerated
	 */
	private String movieDirector;
	/**
	 * @mbggenerated
	 */
	private String moviePicPath;
	/**
	 * @mbggenerated
	 */
	private Float movieScore;
	/**
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * @mbggenerated
	 */
	private String movieDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table superman_movie
	 * @mbggenerated  Thu Dec 08 10:04:22 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * @mbggenerated
	 */
	public String getMovieId() {
		return movieId;
	}

	/**
	 * @param movieId  
	 * @mbggenerated
	 */
	public void setMovieId(String movieId) {
		this.movieId = movieId == null ? null : movieId.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieName() {
		return movieName;
	}

	/**
	 * @param movieName  
	 * @mbggenerated
	 */
	public void setMovieName(String movieName) {
		this.movieName = movieName == null ? null : movieName.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieDirector() {
		return movieDirector;
	}

	/**
	 * @param movieDirector  
	 * @mbggenerated
	 */
	public void setMovieDirector(String movieDirector) {
		this.movieDirector = movieDirector == null ? null : movieDirector.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getMoviePicPath() {
		return moviePicPath;
	}

	/**
	 * @param moviePicPath  
	 * @mbggenerated
	 */
	public void setMoviePicPath(String moviePicPath) {
		this.moviePicPath = moviePicPath == null ? null : moviePicPath.trim();
	}

	/**
	 * @mbggenerated
	 */
	public Float getMovieScore() {
		return movieScore;
	}

	/**
	 * @param movieScore  
	 * @mbggenerated
	 */
	public void setMovieScore(Float movieScore) {
		this.movieScore = movieScore;
	}

	/**
	 * @mbggenerated
	 */
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * @param rowAddTime  
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * @mbggenerated
	 */
	public String getMovieDescription() {
		return movieDescription;
	}

	/**
	 * @param movieDescription  
	 * @mbggenerated
	 */
	public void setMovieDescription(String movieDescription) {
		this.movieDescription = movieDescription == null ? null : movieDescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table superman_movie
	 * @mbggenerated  Thu Dec 08 10:04:22 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", movieId=").append(movieId);
		sb.append(", movieName=").append(movieName);
		sb.append(", movieDirector=").append(movieDirector);
		sb.append(", moviePicPath=").append(moviePicPath);
		sb.append(", movieScore=").append(movieScore);
		sb.append(", rowAddTime=").append(rowAddTime);
		sb.append(", movieDescription=").append(movieDescription);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}