package com.wy.adalliance.dal.thinksns.model;

import java.util.ArrayList;
import java.util.List;

public class TsFeedDataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public TsFeedDataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;
		
		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}
		
		public boolean isValid() {
			return criteria.size() > 0;
		}
		
		public List<Criterion> getAllCriteria() {
			return criteria;
		}
		
		public List<Criterion> getCriteria() {
			return criteria;
		}
		
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}
		
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}
		
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		
		public Criteria andFeedIdIsNull() {
			addCriterion("feed_id is null");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdIsNotNull() {
			addCriterion("feed_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdEqualTo(Integer value) {
			addCriterion("feed_id =", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdNotEqualTo(Integer value) {
			addCriterion("feed_id <>", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdGreaterThan(Integer value) {
			addCriterion("feed_id >", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("feed_id >=", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdLessThan(Integer value) {
			addCriterion("feed_id <", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdLessThanOrEqualTo(Integer value) {
			addCriterion("feed_id <=", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdIn(List<Integer> values) {
			addCriterion("feed_id in", values, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdNotIn(List<Integer> values) {
			addCriterion("feed_id not in", values, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdBetween(Integer value1, Integer value2) {
			addCriterion("feed_id between", value1, value2, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdNotBetween(Integer value1, Integer value2) {
			addCriterion("feed_id not between", value1, value2, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andClientIpIsNull() {
			addCriterion("client_ip is null");
			return (Criteria) this;
		}
		
		public Criteria andClientIpIsNotNull() {
			addCriterion("client_ip is not null");
			return (Criteria) this;
		}
		
		public Criteria andClientIpEqualTo(String value) {
			addCriterion("client_ip =", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpNotEqualTo(String value) {
			addCriterion("client_ip <>", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpGreaterThan(String value) {
			addCriterion("client_ip >", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpGreaterThanOrEqualTo(String value) {
			addCriterion("client_ip >=", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpLessThan(String value) {
			addCriterion("client_ip <", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpLessThanOrEqualTo(String value) {
			addCriterion("client_ip <=", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpLike(String value) {
			addCriterion("client_ip like", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpNotLike(String value) {
			addCriterion("client_ip not like", value, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpIn(List<String> values) {
			addCriterion("client_ip in", values, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpNotIn(List<String> values) {
			addCriterion("client_ip not in", values, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpBetween(String value1, String value2) {
			addCriterion("client_ip between", value1, value2, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientIpNotBetween(String value1, String value2) {
			addCriterion("client_ip not between", value1, value2, "clientIp");
			return (Criteria) this;
		}
		
		public Criteria andClientPortIsNull() {
			addCriterion("client_port is null");
			return (Criteria) this;
		}
		
		public Criteria andClientPortIsNotNull() {
			addCriterion("client_port is not null");
			return (Criteria) this;
		}
		
		public Criteria andClientPortEqualTo(String value) {
			addCriterion("client_port =", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortNotEqualTo(String value) {
			addCriterion("client_port <>", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortGreaterThan(String value) {
			addCriterion("client_port >", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortGreaterThanOrEqualTo(String value) {
			addCriterion("client_port >=", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortLessThan(String value) {
			addCriterion("client_port <", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortLessThanOrEqualTo(String value) {
			addCriterion("client_port <=", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortLike(String value) {
			addCriterion("client_port like", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortNotLike(String value) {
			addCriterion("client_port not like", value, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortIn(List<String> values) {
			addCriterion("client_port in", values, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortNotIn(List<String> values) {
			addCriterion("client_port not in", values, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortBetween(String value1, String value2) {
			addCriterion("client_port between", value1, value2, "clientPort");
			return (Criteria) this;
		}
		
		public Criteria andClientPortNotBetween(String value1, String value2) {
			addCriterion("client_port not between", value1, value2, "clientPort");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;
		
		public String getCondition() {
			return condition;
		}
		
		public Object getValue() {
			return value;
		}
		
		public Object getSecondValue() {
			return secondValue;
		}
		
		public boolean isNoValue() {
			return noValue;
		}
		
		public boolean isSingleValue() {
			return singleValue;
		}
		
		public boolean isBetweenValue() {
			return betweenValue;
		}
		
		public boolean isListValue() {
			return listValue;
		}
		
		public String getTypeHandler() {
			return typeHandler;
		}
		
		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}
		
		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}
		
		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}
		
		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}
		
		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_feed_data
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 21 10:41:11 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}