package com.wy.adalliance.dal.thinksns.model;

import java.io.Serializable;

public class TsFeedDataWithBLOBs extends TsFeedData implements Serializable {

	/**
	 * 关联ts_feed表，动态数据，序列化保存
	 * @mbggenerated
	 */
	private String feedData;
	/**
	 * 纯分享内容
	 * @mbggenerated
	 */
	private String feedContent;
	/**
	 * 分享来源
	 * @mbggenerated
	 */
	private String fromData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 关联ts_feed表，动态数据，序列化保存
	 * @mbggenerated
	 */
	public String getFeedData() {
		return feedData;
	}

	/**
	 * 关联ts_feed表，动态数据，序列化保存
	 * @param feedData  关联ts_feed表，动态数据，序列化保存
	 * @mbggenerated
	 */
	public void setFeedData(String feedData) {
		this.feedData = feedData == null ? null : feedData.trim();
	}

	/**
	 * 纯分享内容
	 * @mbggenerated
	 */
	public String getFeedContent() {
		return feedContent;
	}

	/**
	 * 纯分享内容
	 * @param feedContent  纯分享内容
	 * @mbggenerated
	 */
	public void setFeedContent(String feedContent) {
		this.feedContent = feedContent == null ? null : feedContent.trim();
	}

	/**
	 * 分享来源
	 * @mbggenerated
	 */
	public String getFromData() {
		return fromData;
	}

	/**
	 * 分享来源
	 * @param fromData  分享来源
	 * @mbggenerated
	 */
	public void setFromData(String fromData) {
		this.fromData = fromData == null ? null : fromData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", feedData=").append(feedData);
		sb.append(", feedContent=").append(feedContent);
		sb.append(", fromData=").append(fromData);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}