package com.wy.adalliance.dal.thinksns.model;

import java.util.ArrayList;
import java.util.List;

public class TsFeedExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public TsFeedExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;
		
		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}
		
		public boolean isValid() {
			return criteria.size() > 0;
		}
		
		public List<Criterion> getAllCriteria() {
			return criteria;
		}
		
		public List<Criterion> getCriteria() {
			return criteria;
		}
		
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}
		
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}
		
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		
		public Criteria andFeedIdIsNull() {
			addCriterion("feed_id is null");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdIsNotNull() {
			addCriterion("feed_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdEqualTo(Integer value) {
			addCriterion("feed_id =", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdNotEqualTo(Integer value) {
			addCriterion("feed_id <>", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdGreaterThan(Integer value) {
			addCriterion("feed_id >", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("feed_id >=", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdLessThan(Integer value) {
			addCriterion("feed_id <", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdLessThanOrEqualTo(Integer value) {
			addCriterion("feed_id <=", value, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdIn(List<Integer> values) {
			addCriterion("feed_id in", values, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdNotIn(List<Integer> values) {
			addCriterion("feed_id not in", values, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdBetween(Integer value1, Integer value2) {
			addCriterion("feed_id between", value1, value2, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andFeedIdNotBetween(Integer value1, Integer value2) {
			addCriterion("feed_id not between", value1, value2, "feedId");
			return (Criteria) this;
		}
		
		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}
		
		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}
		
		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}
		
		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}
		
		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}
		
		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}
		
		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}
		
		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}
		
		public Criteria andAppIsNull() {
			addCriterion("app is null");
			return (Criteria) this;
		}
		
		public Criteria andAppIsNotNull() {
			addCriterion("app is not null");
			return (Criteria) this;
		}
		
		public Criteria andAppEqualTo(String value) {
			addCriterion("app =", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppNotEqualTo(String value) {
			addCriterion("app <>", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppGreaterThan(String value) {
			addCriterion("app >", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppGreaterThanOrEqualTo(String value) {
			addCriterion("app >=", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppLessThan(String value) {
			addCriterion("app <", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppLessThanOrEqualTo(String value) {
			addCriterion("app <=", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppLike(String value) {
			addCriterion("app like", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppNotLike(String value) {
			addCriterion("app not like", value, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppIn(List<String> values) {
			addCriterion("app in", values, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppNotIn(List<String> values) {
			addCriterion("app not in", values, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppBetween(String value1, String value2) {
			addCriterion("app between", value1, value2, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppNotBetween(String value1, String value2) {
			addCriterion("app not between", value1, value2, "app");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableIsNull() {
			addCriterion("app_row_table is null");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableIsNotNull() {
			addCriterion("app_row_table is not null");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableEqualTo(String value) {
			addCriterion("app_row_table =", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableNotEqualTo(String value) {
			addCriterion("app_row_table <>", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableGreaterThan(String value) {
			addCriterion("app_row_table >", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableGreaterThanOrEqualTo(String value) {
			addCriterion("app_row_table >=", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableLessThan(String value) {
			addCriterion("app_row_table <", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableLessThanOrEqualTo(String value) {
			addCriterion("app_row_table <=", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableLike(String value) {
			addCriterion("app_row_table like", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableNotLike(String value) {
			addCriterion("app_row_table not like", value, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableIn(List<String> values) {
			addCriterion("app_row_table in", values, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableNotIn(List<String> values) {
			addCriterion("app_row_table not in", values, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableBetween(String value1, String value2) {
			addCriterion("app_row_table between", value1, value2, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowTableNotBetween(String value1, String value2) {
			addCriterion("app_row_table not between", value1, value2, "appRowTable");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdIsNull() {
			addCriterion("app_row_id is null");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdIsNotNull() {
			addCriterion("app_row_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdEqualTo(Integer value) {
			addCriterion("app_row_id =", value, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdNotEqualTo(Integer value) {
			addCriterion("app_row_id <>", value, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdGreaterThan(Integer value) {
			addCriterion("app_row_id >", value, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("app_row_id >=", value, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdLessThan(Integer value) {
			addCriterion("app_row_id <", value, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdLessThanOrEqualTo(Integer value) {
			addCriterion("app_row_id <=", value, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdIn(List<Integer> values) {
			addCriterion("app_row_id in", values, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdNotIn(List<Integer> values) {
			addCriterion("app_row_id not in", values, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdBetween(Integer value1, Integer value2) {
			addCriterion("app_row_id between", value1, value2, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andAppRowIdNotBetween(Integer value1, Integer value2) {
			addCriterion("app_row_id not between", value1, value2, "appRowId");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeIsNull() {
			addCriterion("publish_time is null");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeIsNotNull() {
			addCriterion("publish_time is not null");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeEqualTo(Integer value) {
			addCriterion("publish_time =", value, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeNotEqualTo(Integer value) {
			addCriterion("publish_time <>", value, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeGreaterThan(Integer value) {
			addCriterion("publish_time >", value, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("publish_time >=", value, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeLessThan(Integer value) {
			addCriterion("publish_time <", value, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeLessThanOrEqualTo(Integer value) {
			addCriterion("publish_time <=", value, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeIn(List<Integer> values) {
			addCriterion("publish_time in", values, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeNotIn(List<Integer> values) {
			addCriterion("publish_time not in", values, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeBetween(Integer value1, Integer value2) {
			addCriterion("publish_time between", value1, value2, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andPublishTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("publish_time not between", value1, value2, "publishTime");
			return (Criteria) this;
		}
		
		public Criteria andIsDelIsNull() {
			addCriterion("is_del is null");
			return (Criteria) this;
		}
		
		public Criteria andIsDelIsNotNull() {
			addCriterion("is_del is not null");
			return (Criteria) this;
		}
		
		public Criteria andIsDelEqualTo(Integer value) {
			addCriterion("is_del =", value, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelNotEqualTo(Integer value) {
			addCriterion("is_del <>", value, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelGreaterThan(Integer value) {
			addCriterion("is_del >", value, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_del >=", value, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelLessThan(Integer value) {
			addCriterion("is_del <", value, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelLessThanOrEqualTo(Integer value) {
			addCriterion("is_del <=", value, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelIn(List<Integer> values) {
			addCriterion("is_del in", values, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelNotIn(List<Integer> values) {
			addCriterion("is_del not in", values, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelBetween(Integer value1, Integer value2) {
			addCriterion("is_del between", value1, value2, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
			addCriterion("is_del not between", value1, value2, "isDel");
			return (Criteria) this;
		}
		
		public Criteria andFromIsNull() {
			addCriterion("from is null");
			return (Criteria) this;
		}
		
		public Criteria andFromIsNotNull() {
			addCriterion("from is not null");
			return (Criteria) this;
		}
		
		public Criteria andFromEqualTo(Byte value) {
			addCriterion("from =", value, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromNotEqualTo(Byte value) {
			addCriterion("from <>", value, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromGreaterThan(Byte value) {
			addCriterion("from >", value, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromGreaterThanOrEqualTo(Byte value) {
			addCriterion("from >=", value, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromLessThan(Byte value) {
			addCriterion("from <", value, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromLessThanOrEqualTo(Byte value) {
			addCriterion("from <=", value, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromIn(List<Byte> values) {
			addCriterion("from in", values, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromNotIn(List<Byte> values) {
			addCriterion("from not in", values, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromBetween(Byte value1, Byte value2) {
			addCriterion("from between", value1, value2, "from");
			return (Criteria) this;
		}
		
		public Criteria andFromNotBetween(Byte value1, Byte value2) {
			addCriterion("from not between", value1, value2, "from");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountIsNull() {
			addCriterion("comment_count is null");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountIsNotNull() {
			addCriterion("comment_count is not null");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountEqualTo(Integer value) {
			addCriterion("comment_count =", value, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountNotEqualTo(Integer value) {
			addCriterion("comment_count <>", value, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountGreaterThan(Integer value) {
			addCriterion("comment_count >", value, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("comment_count >=", value, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountLessThan(Integer value) {
			addCriterion("comment_count <", value, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
			addCriterion("comment_count <=", value, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountIn(List<Integer> values) {
			addCriterion("comment_count in", values, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountNotIn(List<Integer> values) {
			addCriterion("comment_count not in", values, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountBetween(Integer value1, Integer value2) {
			addCriterion("comment_count between", value1, value2, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
			addCriterion("comment_count not between", value1, value2, "commentCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountIsNull() {
			addCriterion("repost_count is null");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountIsNotNull() {
			addCriterion("repost_count is not null");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountEqualTo(Integer value) {
			addCriterion("repost_count =", value, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountNotEqualTo(Integer value) {
			addCriterion("repost_count <>", value, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountGreaterThan(Integer value) {
			addCriterion("repost_count >", value, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("repost_count >=", value, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountLessThan(Integer value) {
			addCriterion("repost_count <", value, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountLessThanOrEqualTo(Integer value) {
			addCriterion("repost_count <=", value, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountIn(List<Integer> values) {
			addCriterion("repost_count in", values, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountNotIn(List<Integer> values) {
			addCriterion("repost_count not in", values, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountBetween(Integer value1, Integer value2) {
			addCriterion("repost_count between", value1, value2, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andRepostCountNotBetween(Integer value1, Integer value2) {
			addCriterion("repost_count not between", value1, value2, "repostCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountIsNull() {
			addCriterion("comment_all_count is null");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountIsNotNull() {
			addCriterion("comment_all_count is not null");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountEqualTo(Integer value) {
			addCriterion("comment_all_count =", value, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountNotEqualTo(Integer value) {
			addCriterion("comment_all_count <>", value, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountGreaterThan(Integer value) {
			addCriterion("comment_all_count >", value, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("comment_all_count >=", value, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountLessThan(Integer value) {
			addCriterion("comment_all_count <", value, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountLessThanOrEqualTo(Integer value) {
			addCriterion("comment_all_count <=", value, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountIn(List<Integer> values) {
			addCriterion("comment_all_count in", values, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountNotIn(List<Integer> values) {
			addCriterion("comment_all_count not in", values, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountBetween(Integer value1, Integer value2) {
			addCriterion("comment_all_count between", value1, value2, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andCommentAllCountNotBetween(Integer value1, Integer value2) {
			addCriterion("comment_all_count not between", value1, value2, "commentAllCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountIsNull() {
			addCriterion("digg_count is null");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountIsNotNull() {
			addCriterion("digg_count is not null");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountEqualTo(Integer value) {
			addCriterion("digg_count =", value, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountNotEqualTo(Integer value) {
			addCriterion("digg_count <>", value, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountGreaterThan(Integer value) {
			addCriterion("digg_count >", value, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("digg_count >=", value, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountLessThan(Integer value) {
			addCriterion("digg_count <", value, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountLessThanOrEqualTo(Integer value) {
			addCriterion("digg_count <=", value, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountIn(List<Integer> values) {
			addCriterion("digg_count in", values, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountNotIn(List<Integer> values) {
			addCriterion("digg_count not in", values, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountBetween(Integer value1, Integer value2) {
			addCriterion("digg_count between", value1, value2, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andDiggCountNotBetween(Integer value1, Integer value2) {
			addCriterion("digg_count not between", value1, value2, "diggCount");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostIsNull() {
			addCriterion("is_repost is null");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostIsNotNull() {
			addCriterion("is_repost is not null");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostEqualTo(Integer value) {
			addCriterion("is_repost =", value, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostNotEqualTo(Integer value) {
			addCriterion("is_repost <>", value, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostGreaterThan(Integer value) {
			addCriterion("is_repost >", value, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_repost >=", value, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostLessThan(Integer value) {
			addCriterion("is_repost <", value, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostLessThanOrEqualTo(Integer value) {
			addCriterion("is_repost <=", value, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostIn(List<Integer> values) {
			addCriterion("is_repost in", values, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostNotIn(List<Integer> values) {
			addCriterion("is_repost not in", values, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostBetween(Integer value1, Integer value2) {
			addCriterion("is_repost between", value1, value2, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsRepostNotBetween(Integer value1, Integer value2) {
			addCriterion("is_repost not between", value1, value2, "isRepost");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditIsNull() {
			addCriterion("is_audit is null");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditIsNotNull() {
			addCriterion("is_audit is not null");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditEqualTo(Integer value) {
			addCriterion("is_audit =", value, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditNotEqualTo(Integer value) {
			addCriterion("is_audit <>", value, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditGreaterThan(Integer value) {
			addCriterion("is_audit >", value, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_audit >=", value, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditLessThan(Integer value) {
			addCriterion("is_audit <", value, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditLessThanOrEqualTo(Integer value) {
			addCriterion("is_audit <=", value, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditIn(List<Integer> values) {
			addCriterion("is_audit in", values, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditNotIn(List<Integer> values) {
			addCriterion("is_audit not in", values, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditBetween(Integer value1, Integer value2) {
			addCriterion("is_audit between", value1, value2, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andIsAuditNotBetween(Integer value1, Integer value2) {
			addCriterion("is_audit not between", value1, value2, "isAudit");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeIsNull() {
			addCriterion("latitude is null");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeIsNotNull() {
			addCriterion("latitude is not null");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeEqualTo(Float value) {
			addCriterion("latitude =", value, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeNotEqualTo(Float value) {
			addCriterion("latitude <>", value, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeGreaterThan(Float value) {
			addCriterion("latitude >", value, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeGreaterThanOrEqualTo(Float value) {
			addCriterion("latitude >=", value, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeLessThan(Float value) {
			addCriterion("latitude <", value, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeLessThanOrEqualTo(Float value) {
			addCriterion("latitude <=", value, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeIn(List<Float> values) {
			addCriterion("latitude in", values, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeNotIn(List<Float> values) {
			addCriterion("latitude not in", values, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeBetween(Float value1, Float value2) {
			addCriterion("latitude between", value1, value2, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLatitudeNotBetween(Float value1, Float value2) {
			addCriterion("latitude not between", value1, value2, "latitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeIsNull() {
			addCriterion("longitude is null");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeIsNotNull() {
			addCriterion("longitude is not null");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeEqualTo(Float value) {
			addCriterion("longitude =", value, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeNotEqualTo(Float value) {
			addCriterion("longitude <>", value, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeGreaterThan(Float value) {
			addCriterion("longitude >", value, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeGreaterThanOrEqualTo(Float value) {
			addCriterion("longitude >=", value, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeLessThan(Float value) {
			addCriterion("longitude <", value, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeLessThanOrEqualTo(Float value) {
			addCriterion("longitude <=", value, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeIn(List<Float> values) {
			addCriterion("longitude in", values, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeNotIn(List<Float> values) {
			addCriterion("longitude not in", values, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeBetween(Float value1, Float value2) {
			addCriterion("longitude between", value1, value2, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andLongitudeNotBetween(Float value1, Float value2) {
			addCriterion("longitude not between", value1, value2, "longitude");
			return (Criteria) this;
		}
		
		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}
		
		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}
		
		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}
		
		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendIsNull() {
			addCriterion("is_recommend is null");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendIsNotNull() {
			addCriterion("is_recommend is not null");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendEqualTo(Byte value) {
			addCriterion("is_recommend =", value, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendNotEqualTo(Byte value) {
			addCriterion("is_recommend <>", value, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendGreaterThan(Byte value) {
			addCriterion("is_recommend >", value, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendGreaterThanOrEqualTo(Byte value) {
			addCriterion("is_recommend >=", value, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendLessThan(Byte value) {
			addCriterion("is_recommend <", value, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendLessThanOrEqualTo(Byte value) {
			addCriterion("is_recommend <=", value, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendIn(List<Byte> values) {
			addCriterion("is_recommend in", values, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendNotIn(List<Byte> values) {
			addCriterion("is_recommend not in", values, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendBetween(Byte value1, Byte value2) {
			addCriterion("is_recommend between", value1, value2, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andIsRecommendNotBetween(Byte value1, Byte value2) {
			addCriterion("is_recommend not between", value1, value2, "isRecommend");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeIsNull() {
			addCriterion("recommend_time is null");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeIsNotNull() {
			addCriterion("recommend_time is not null");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeEqualTo(Integer value) {
			addCriterion("recommend_time =", value, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeNotEqualTo(Integer value) {
			addCriterion("recommend_time <>", value, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeGreaterThan(Integer value) {
			addCriterion("recommend_time >", value, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("recommend_time >=", value, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeLessThan(Integer value) {
			addCriterion("recommend_time <", value, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeLessThanOrEqualTo(Integer value) {
			addCriterion("recommend_time <=", value, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeIn(List<Integer> values) {
			addCriterion("recommend_time in", values, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeNotIn(List<Integer> values) {
			addCriterion("recommend_time not in", values, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeBetween(Integer value1, Integer value2) {
			addCriterion("recommend_time between", value1, value2, "recommendTime");
			return (Criteria) this;
		}
		
		public Criteria andRecommendTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("recommend_time not between", value1, value2, "recommendTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;
		
		public String getCondition() {
			return condition;
		}
		
		public Object getValue() {
			return value;
		}
		
		public Object getSecondValue() {
			return secondValue;
		}
		
		public boolean isNoValue() {
			return noValue;
		}
		
		public boolean isSingleValue() {
			return singleValue;
		}
		
		public boolean isBetweenValue() {
			return betweenValue;
		}
		
		public boolean isListValue() {
			return listValue;
		}
		
		public String getTypeHandler() {
			return typeHandler;
		}
		
		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}
		
		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}
		
		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}
		
		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}
		
		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_feed
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 21 10:41:11 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}