package com.wy.adalliance.dal.thinksns.model;

import java.io.Serializable;

public class TsFeedData implements Serializable {

	/**
	 * 关联ts_feed表，feed_id
	 * @mbggenerated
	 */
	private Integer feedId;
	/**
	 * 客户端IP
	 * @mbggenerated
	 */
	private String clientIp;
	/**
	 * @mbggenerated
	 */
	private String clientPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 关联ts_feed表，feed_id
	 * @mbggenerated
	 */
	public Integer getFeedId() {
		return feedId;
	}

	/**
	 * 关联ts_feed表，feed_id
	 * @param feedId  关联ts_feed表，feed_id
	 * @mbggenerated
	 */
	public void setFeedId(Integer feedId) {
		this.feedId = feedId;
	}

	/**
	 * 客户端IP
	 * @mbggenerated
	 */
	public String getClientIp() {
		return clientIp;
	}

	/**
	 * 客户端IP
	 * @param clientIp  客户端IP
	 * @mbggenerated
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp == null ? null : clientIp.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getClientPort() {
		return clientPort;
	}

	/**
	 * @param clientPort  
	 * @mbggenerated
	 */
	public void setClientPort(String clientPort) {
		this.clientPort = clientPort == null ? null : clientPort.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", feedId=").append(feedId);
		sb.append(", clientIp=").append(clientIp);
		sb.append(", clientPort=").append(clientPort);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}