package com.wy.adalliance.dal.thinksns.model;

import java.io.Serializable;

public class TsUser implements Serializable {

	/**
	 * 主键UID
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * 手机号码
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * 用户密码的md5摘要
	 * @mbggenerated
	 */
	private String password;
	/**
	 * 10000 到 99999之间的随机数，加密密码时使用
	 * @mbggenerated
	 */
	private String loginSalt;
	/**
	 * 用户名
	 * @mbggenerated
	 */
	private String uname;
	/**
	 * 用户email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * 性别 1：男、2：女
	 * @mbggenerated
	 */
	private Boolean sex;
	/**
	 * 所在省市的字符串
	 * @mbggenerated
	 */
	private String location;
	/**
	 * 是否通过审核：0-未通过，1-已通过
	 * @mbggenerated
	 */
	private Boolean isAudit;
	/**
	 * 是否已激活 1：激活、0：未激活
	 * @mbggenerated
	 */
	private Boolean isActive;
	/**
	 * 是否初始化用户资料 1：初始化、0：未初始化
	 * @mbggenerated
	 */
	private Boolean isInit;
	/**
	 * 注册时间
	 * @mbggenerated
	 */
	private Integer ctime;
	/**
	 * 身份标识（1：用户，2：组织）
	 * @mbggenerated
	 */
	private Boolean identity;
	/**
	 * 用户的api_key用于移动端
	 * @mbggenerated
	 */
	private String apiKey;
	/**
	 * 保留字段，用于用户分表
	 * @mbggenerated
	 */
	private String domain;
	/**
	 * 省ID、关联ts_area表
	 * @mbggenerated
	 */
	private Integer province;
	/**
	 * 城市ID，关联ts_area表
	 * @mbggenerated
	 */
	private Integer city;
	/**
	 * 地区ID，关联ts_area表
	 * @mbggenerated
	 */
	private Integer area;
	/**
	 * 册注IP
	 * @mbggenerated
	 */
	private String regIp;
	/**
	 * 言语
	 * @mbggenerated
	 */
	private String lang;
	/**
	 * 时区
	 * @mbggenerated
	 */
	private String timezone;
	/**
	 * 是否禁用，0不禁用，1：禁用
	 * @mbggenerated
	 */
	private Byte isDel;
	/**
	 * 用户名称的首字母
	 * @mbggenerated
	 */
	private String firstLetter;
	/**
	 * 户用简介
	 * @mbggenerated
	 */
	private String intro;
	/**
	 * 户用最后一次登录时间
	 * @mbggenerated
	 */
	private Integer lastLoginTime;
	/**
	 * 户用最后发表的分享ID
	 * @mbggenerated
	 */
	private Integer lastFeedId;
	/**
	 * 户用最后发表分享的时间
	 * @mbggenerated
	 */
	private Integer lastPostTime;
	/**
	 * 搜索字段
	 * @mbggenerated
	 */
	private String searchKey;
	/**
	 * 邀请注册码
	 * @mbggenerated
	 */
	private String inviteCode;
	/**
	 * @mbggenerated
	 */
	private Integer feedEmailTime;
	/**
	 * @mbggenerated
	 */
	private Integer sendEmailTime;
	/**
	 * @mbggenerated
	 */
	private String openid;
	/**
	 * 手动提交地址
	 * @mbggenerated
	 */
	private String inputCity;
	/**
	 * 分享框固定为发布状态
	 * @mbggenerated
	 */
	private Boolean isFixed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 主键UID
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * 主键UID
	 * @param uid  主键UID
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * 手机号码
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * 手机号码
	 * @param phone  手机号码
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * 用户密码的md5摘要
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * 用户密码的md5摘要
	 * @param password  用户密码的md5摘要
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * 10000 到 99999之间的随机数，加密密码时使用
	 * @mbggenerated
	 */
	public String getLoginSalt() {
		return loginSalt;
	}

	/**
	 * 10000 到 99999之间的随机数，加密密码时使用
	 * @param loginSalt  10000 到 99999之间的随机数，加密密码时使用
	 * @mbggenerated
	 */
	public void setLoginSalt(String loginSalt) {
		this.loginSalt = loginSalt == null ? null : loginSalt.trim();
	}

	/**
	 * 用户名
	 * @mbggenerated
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * 用户名
	 * @param uname  用户名
	 * @mbggenerated
	 */
	public void setUname(String uname) {
		this.uname = uname == null ? null : uname.trim();
	}

	/**
	 * 用户email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * 用户email
	 * @param email  用户email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * 性别 1：男、2：女
	 * @mbggenerated
	 */
	public Boolean getSex() {
		return sex;
	}

	/**
	 * 性别 1：男、2：女
	 * @param sex  性别 1：男、2：女
	 * @mbggenerated
	 */
	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	/**
	 * 所在省市的字符串
	 * @mbggenerated
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * 所在省市的字符串
	 * @param location  所在省市的字符串
	 * @mbggenerated
	 */
	public void setLocation(String location) {
		this.location = location == null ? null : location.trim();
	}

	/**
	 * 是否通过审核：0-未通过，1-已通过
	 * @mbggenerated
	 */
	public Boolean getIsAudit() {
		return isAudit;
	}

	/**
	 * 是否通过审核：0-未通过，1-已通过
	 * @param isAudit  是否通过审核：0-未通过，1-已通过
	 * @mbggenerated
	 */
	public void setIsAudit(Boolean isAudit) {
		this.isAudit = isAudit;
	}

	/**
	 * 是否已激活 1：激活、0：未激活
	 * @mbggenerated
	 */
	public Boolean getIsActive() {
		return isActive;
	}

	/**
	 * 是否已激活 1：激活、0：未激活
	 * @param isActive  是否已激活 1：激活、0：未激活
	 * @mbggenerated
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	/**
	 * 是否初始化用户资料 1：初始化、0：未初始化
	 * @mbggenerated
	 */
	public Boolean getIsInit() {
		return isInit;
	}

	/**
	 * 是否初始化用户资料 1：初始化、0：未初始化
	 * @param isInit  是否初始化用户资料 1：初始化、0：未初始化
	 * @mbggenerated
	 */
	public void setIsInit(Boolean isInit) {
		this.isInit = isInit;
	}

	/**
	 * 注册时间
	 * @mbggenerated
	 */
	public Integer getCtime() {
		return ctime;
	}

	/**
	 * 注册时间
	 * @param ctime  注册时间
	 * @mbggenerated
	 */
	public void setCtime(Integer ctime) {
		this.ctime = ctime;
	}

	/**
	 * 身份标识（1：用户，2：组织）
	 * @mbggenerated
	 */
	public Boolean getIdentity() {
		return identity;
	}

	/**
	 * 身份标识（1：用户，2：组织）
	 * @param identity  身份标识（1：用户，2：组织）
	 * @mbggenerated
	 */
	public void setIdentity(Boolean identity) {
		this.identity = identity;
	}

	/**
	 * 用户的api_key用于移动端
	 * @mbggenerated
	 */
	public String getApiKey() {
		return apiKey;
	}

	/**
	 * 用户的api_key用于移动端
	 * @param apiKey  用户的api_key用于移动端
	 * @mbggenerated
	 */
	public void setApiKey(String apiKey) {
		this.apiKey = apiKey == null ? null : apiKey.trim();
	}

	/**
	 * 保留字段，用于用户分表
	 * @mbggenerated
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * 保留字段，用于用户分表
	 * @param domain  保留字段，用于用户分表
	 * @mbggenerated
	 */
	public void setDomain(String domain) {
		this.domain = domain == null ? null : domain.trim();
	}

	/**
	 * 省ID、关联ts_area表
	 * @mbggenerated
	 */
	public Integer getProvince() {
		return province;
	}

	/**
	 * 省ID、关联ts_area表
	 * @param province  省ID、关联ts_area表
	 * @mbggenerated
	 */
	public void setProvince(Integer province) {
		this.province = province;
	}

	/**
	 * 城市ID，关联ts_area表
	 * @mbggenerated
	 */
	public Integer getCity() {
		return city;
	}

	/**
	 * 城市ID，关联ts_area表
	 * @param city  城市ID，关联ts_area表
	 * @mbggenerated
	 */
	public void setCity(Integer city) {
		this.city = city;
	}

	/**
	 * 地区ID，关联ts_area表
	 * @mbggenerated
	 */
	public Integer getArea() {
		return area;
	}

	/**
	 * 地区ID，关联ts_area表
	 * @param area  地区ID，关联ts_area表
	 * @mbggenerated
	 */
	public void setArea(Integer area) {
		this.area = area;
	}

	/**
	 * 册注IP
	 * @mbggenerated
	 */
	public String getRegIp() {
		return regIp;
	}

	/**
	 * 册注IP
	 * @param regIp  册注IP
	 * @mbggenerated
	 */
	public void setRegIp(String regIp) {
		this.regIp = regIp == null ? null : regIp.trim();
	}

	/**
	 * 言语
	 * @mbggenerated
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * 言语
	 * @param lang  言语
	 * @mbggenerated
	 */
	public void setLang(String lang) {
		this.lang = lang == null ? null : lang.trim();
	}

	/**
	 * 时区
	 * @mbggenerated
	 */
	public String getTimezone() {
		return timezone;
	}

	/**
	 * 时区
	 * @param timezone  时区
	 * @mbggenerated
	 */
	public void setTimezone(String timezone) {
		this.timezone = timezone == null ? null : timezone.trim();
	}

	/**
	 * 是否禁用，0不禁用，1：禁用
	 * @mbggenerated
	 */
	public Byte getIsDel() {
		return isDel;
	}

	/**
	 * 是否禁用，0不禁用，1：禁用
	 * @param isDel  是否禁用，0不禁用，1：禁用
	 * @mbggenerated
	 */
	public void setIsDel(Byte isDel) {
		this.isDel = isDel;
	}

	/**
	 * 用户名称的首字母
	 * @mbggenerated
	 */
	public String getFirstLetter() {
		return firstLetter;
	}

	/**
	 * 用户名称的首字母
	 * @param firstLetter  用户名称的首字母
	 * @mbggenerated
	 */
	public void setFirstLetter(String firstLetter) {
		this.firstLetter = firstLetter == null ? null : firstLetter.trim();
	}

	/**
	 * 户用简介
	 * @mbggenerated
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * 户用简介
	 * @param intro  户用简介
	 * @mbggenerated
	 */
	public void setIntro(String intro) {
		this.intro = intro == null ? null : intro.trim();
	}

	/**
	 * 户用最后一次登录时间
	 * @mbggenerated
	 */
	public Integer getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * 户用最后一次登录时间
	 * @param lastLoginTime  户用最后一次登录时间
	 * @mbggenerated
	 */
	public void setLastLoginTime(Integer lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * 户用最后发表的分享ID
	 * @mbggenerated
	 */
	public Integer getLastFeedId() {
		return lastFeedId;
	}

	/**
	 * 户用最后发表的分享ID
	 * @param lastFeedId  户用最后发表的分享ID
	 * @mbggenerated
	 */
	public void setLastFeedId(Integer lastFeedId) {
		this.lastFeedId = lastFeedId;
	}

	/**
	 * 户用最后发表分享的时间
	 * @mbggenerated
	 */
	public Integer getLastPostTime() {
		return lastPostTime;
	}

	/**
	 * 户用最后发表分享的时间
	 * @param lastPostTime  户用最后发表分享的时间
	 * @mbggenerated
	 */
	public void setLastPostTime(Integer lastPostTime) {
		this.lastPostTime = lastPostTime;
	}

	/**
	 * 搜索字段
	 * @mbggenerated
	 */
	public String getSearchKey() {
		return searchKey;
	}

	/**
	 * 搜索字段
	 * @param searchKey  搜索字段
	 * @mbggenerated
	 */
	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey == null ? null : searchKey.trim();
	}

	/**
	 * 邀请注册码
	 * @mbggenerated
	 */
	public String getInviteCode() {
		return inviteCode;
	}

	/**
	 * 邀请注册码
	 * @param inviteCode  邀请注册码
	 * @mbggenerated
	 */
	public void setInviteCode(String inviteCode) {
		this.inviteCode = inviteCode == null ? null : inviteCode.trim();
	}

	/**
	 * @mbggenerated
	 */
	public Integer getFeedEmailTime() {
		return feedEmailTime;
	}

	/**
	 * @param feedEmailTime  
	 * @mbggenerated
	 */
	public void setFeedEmailTime(Integer feedEmailTime) {
		this.feedEmailTime = feedEmailTime;
	}

	/**
	 * @mbggenerated
	 */
	public Integer getSendEmailTime() {
		return sendEmailTime;
	}

	/**
	 * @param sendEmailTime  
	 * @mbggenerated
	 */
	public void setSendEmailTime(Integer sendEmailTime) {
		this.sendEmailTime = sendEmailTime;
	}

	/**
	 * @mbggenerated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * @param openid  
	 * @mbggenerated
	 */
	public void setOpenid(String openid) {
		this.openid = openid == null ? null : openid.trim();
	}

	/**
	 * 手动提交地址
	 * @mbggenerated
	 */
	public String getInputCity() {
		return inputCity;
	}

	/**
	 * 手动提交地址
	 * @param inputCity  手动提交地址
	 * @mbggenerated
	 */
	public void setInputCity(String inputCity) {
		this.inputCity = inputCity == null ? null : inputCity.trim();
	}

	/**
	 * 分享框固定为发布状态
	 * @mbggenerated
	 */
	public Boolean getIsFixed() {
		return isFixed;
	}

	/**
	 * 分享框固定为发布状态
	 * @param isFixed  分享框固定为发布状态
	 * @mbggenerated
	 */
	public void setIsFixed(Boolean isFixed) {
		this.isFixed = isFixed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", uid=").append(uid);
		sb.append(", phone=").append(phone);
		sb.append(", password=").append(password);
		sb.append(", loginSalt=").append(loginSalt);
		sb.append(", uname=").append(uname);
		sb.append(", email=").append(email);
		sb.append(", sex=").append(sex);
		sb.append(", location=").append(location);
		sb.append(", isAudit=").append(isAudit);
		sb.append(", isActive=").append(isActive);
		sb.append(", isInit=").append(isInit);
		sb.append(", ctime=").append(ctime);
		sb.append(", identity=").append(identity);
		sb.append(", apiKey=").append(apiKey);
		sb.append(", domain=").append(domain);
		sb.append(", province=").append(province);
		sb.append(", city=").append(city);
		sb.append(", area=").append(area);
		sb.append(", regIp=").append(regIp);
		sb.append(", lang=").append(lang);
		sb.append(", timezone=").append(timezone);
		sb.append(", isDel=").append(isDel);
		sb.append(", firstLetter=").append(firstLetter);
		sb.append(", intro=").append(intro);
		sb.append(", lastLoginTime=").append(lastLoginTime);
		sb.append(", lastFeedId=").append(lastFeedId);
		sb.append(", lastPostTime=").append(lastPostTime);
		sb.append(", searchKey=").append(searchKey);
		sb.append(", inviteCode=").append(inviteCode);
		sb.append(", feedEmailTime=").append(feedEmailTime);
		sb.append(", sendEmailTime=").append(sendEmailTime);
		sb.append(", openid=").append(openid);
		sb.append(", inputCity=").append(inputCity);
		sb.append(", isFixed=").append(isFixed);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}