package com.wy.adalliance.dal.thinksns.maps;

import com.wy.adalliance.dal.thinksns.model.TsFeed;
import com.wy.adalliance.dal.thinksns.model.TsFeedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TsFeedMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int countByExample(TsFeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int deleteByExample(TsFeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int deleteByPrimaryKey(Integer feedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int insert(TsFeed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int insertSelective(TsFeed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsFeed> selectByExampleWithRowbounds(TsFeedExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsFeed> selectByExample(TsFeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	TsFeed selectByPrimaryKey(Integer feedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TsFeed record,
									@Param("example") TsFeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByExample(@Param("record") TsFeed record, @Param("example") TsFeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByPrimaryKeySelective(TsFeed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByPrimaryKey(TsFeed record);
}