package com.wy.adalliance.dal.thinksns.maps;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.wy.adalliance.dal.thinksns.model.TsFeedData;
import com.wy.adalliance.dal.thinksns.model.TsFeedDataExample;
import com.wy.adalliance.dal.thinksns.model.TsFeedDataWithBLOBs;

public interface TsFeedDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int countByExample(TsFeedDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int deleteByExample(TsFeedDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int deleteByPrimaryKey(Integer feedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int insert(TsFeedDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int insertSelective(TsFeedDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsFeedDataWithBLOBs> selectByExampleWithBLOBsWithRowbounds(TsFeedDataExample example,
																	RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsFeedDataWithBLOBs> selectByExampleWithBLOBs(TsFeedDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsFeedData> selectByExampleWithRowbounds(TsFeedDataExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsFeedData> selectByExample(TsFeedDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	TsFeedDataWithBLOBs selectByPrimaryKey(Integer feedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TsFeedDataWithBLOBs record,
									@Param("example") TsFeedDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") TsFeedDataWithBLOBs record,
									@Param("example") TsFeedDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByExample(@Param("record") TsFeedData record,
						@Param("example") TsFeedDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByPrimaryKeySelective(TsFeedDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(TsFeedDataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_feed_data
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByPrimaryKey(TsFeedData record);
	
	List<Map<String,String>> queryWeiboByDate(Map<String, Object> params);
}