package com.wy.adalliance.dal.thinksns.maps;

import com.wy.adalliance.dal.thinksns.model.TsUser;
import com.wy.adalliance.dal.thinksns.model.TsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TsUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int countByExample(TsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int deleteByExample(TsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int deleteByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int insert(TsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int insertSelective(TsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsUser> selectByExampleWithRowbounds(TsUserExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	List<TsUser> selectByExample(TsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	TsUser selectByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TsUser record,
									@Param("example") TsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByExample(@Param("record") TsUser record, @Param("example") TsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByPrimaryKeySelective(TsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ts_user
	 * @mbggenerated  Thu Jul 21 10:43:12 CST 2016
	 */
	int updateByPrimaryKey(TsUser record);
}